<a href="https://colab.research.google.com/github/Akhilesh1118/Python/blob/main/Lecture%208/Chapter_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DataFrame Methods
---
We have a lot of useful methods with DataFrame.

**Data Viewing & Inspection**\
These help us take a quick look at our dataset.


1.`df.head(n)` - Shows the first n rows (default = 5)


2. `df.tail(n)` - Shows the last n rows (default = 5)


3. `df.sample(n)` - Shows random n rows (default = 1)


4. `df.info()` -  Displays column names, data types, memory usage


5. `df.describe(n)` - Shows descriptive statistics for numeric columns.


6. `df.nunique()` - Shows count of distinct values exist in each column.


   We also have attributes like :

1. `df.shape` -  Returns (rows, columns).

2. `df.columns` - List of column names.

3. `df.dtypes` - Data types of each column.

In [3]:
import pandas as pd

In [43]:
data = {
'Name': ['Aarav', 'Isha', 'Rohan', 'Sneha', 'Vikram'],
'Age': [25, 30, 35, 40, 45],
'City': ['Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 'Chennai']
}
df = pd.DataFrame(data)
print(df.head())
print(df.tail())
print(df.sample())
print(df.info())
print(df.describe())
print(df.nunique())
print(df.dtypes)
print(df.shape)
print(df.columns)

Index(['Name', 'Age', 'City'], dtype='object')

In [46]:
# Read data with the help of CSV file
df = pd.read_csv("globalAirQuality.csv")
print(df)

                        timestamp country      city  latitude  longitude  \
0      2025-11-04 18:25:17.554219      US  New York    40.713    -74.006
1      2025-11-04 19:25:17.554219      US  New York    40.713    -74.006
2      2025-11-04 20:25:17.554219      US  New York    40.713    -74.006
3      2025-11-04 21:25:17.554219      US  New York    40.713    -74.006
4      2025-11-04 22:25:17.554219      US  New York    40.713    -74.006
...                           ...     ...       ...       ...        ...
17995  2025-11-19 13:25:17.554219      CH    Zurich    47.377      8.542
17996  2025-11-19 14:25:17.554219      CH    Zurich    47.377      8.542
17997  2025-11-19 15:25:17.554219      CH    Zurich    47.377      8.542
17998  2025-11-19 16:25:17.554219      CH    Zurich    47.377      8.542
17999  2025-11-19 17:25:17.554219      CH    Zurich    47.377      8.542

         pm25     pm10     no2    so2      o3     co  aqi  temperature  \
0      50.295  108.938  27.998  6.539  52.568  1.096  108       18.504
1      32.083   63.043  36.120  4.021  43.536  1.075   90        5.838
2      42.250   82.553  26.935  9.538  23.320  0.977   84       31.833
3      30.403   79.951  63.536  7.609  31.369  0.230  158       23.140
4      21.083   66.423  38.997  6.919  45.615  1.085   97       13.632
...       ...      ...     ...    ...     ...    ...  ...          ...
17995  27.899   74.179  41.474  6.677  50.869  1.028  103        7.079
17996   2.950   47.988  42.235  2.821  35.551  0.644  105       28.734
17997  61.347   72.908  46.976  5.763  66.492  0.947  122       21.951
17998  40.722   95.152  32.957  5.524  53.193  0.868   95       24.042
17999  25.830   30.411  35.317  4.336  66.246  0.848   88        8.529

       humidity  wind_speed
0        70.168       3.725
1        80.088       8.969
2        62.783       9.650
3        89.153       8.956
4        76.499       4.017
...         ...         ...
17995    52.443       7.452
17996    85.678       4.496
17997    72.311       9.660
17998    31.880       2.642
17999    59.104       4.403

[18000 rows x 15 columns]

# 2. Indexing & Data Selection
* **Selecting Columns**\
We can select by column name (as a Series) or multiple columns at once.

In [47]:
df["country"]        # returns a Series
df[["city", "aqi"]]  # returns a DataFrame

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

*  **Selecting Rows** \
By index label ( **loc**) - Use row labels (if you have custom index) or column names. \
Note : In  **loc** , when we slice, the ending index is **inclusive**.

In [48]:
df.loc[0]            # 1st row (by label)
df.loc[0:3]          # row0 to row3 - both inclusive in loc

df.loc[0, "country"] # 0th row & specific column

'US'

By index position ( **iloc** ) - Use integer positions. \
Note : In **iloc** , when we slice, the ending index is NOT inclusive.

In [50]:
df.iloc[0]     # 1st row
df.iloc[4:7]   #  4,5,6 row
df.iloc[0, 2]  # 1st row & 3rd column (by position)


# output of df.iloc[4:7]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
5,2025-11-04 23:25:17.554219,US,New York,40.713,-74.006,31.242,92.779,30.633,8.030,43.725,0.347,92,15.159,42.505,1.199
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542

* **Selecting single Cell** \
We have `at` & `iat` for fast access to single cells.

In [39]:
# Select single scalar value
df.at[0, "city"]
df.iat[0, 2]

'New York'

## loc vs iloc

| loc | iloc |
|------|------|
| Label Based | Position Based |
| End Index Included | End Index Excluded |
| Uses Names | Uses Numbers |

# 3. Filtering & Querying Data
* **Boolean Filtering** \
1. We can filter a DataFrame using a condition that returns a boolean Series.

 2. We can use `&` for AND, `|` for OR & wrap each condition in parentheses `()`.

## Query String Rules:
 1. Query returns a **COPY**, not a **VIEW**.
 2. We write the condition in a string.
 3. We can use operators like `and , or, not, ==, != , > , < , >=, <= , etc.`
 4. Use backticks for column names with spaces or symbols.
 5. Use @ for Python variables.

## Important - Rule of thumb:

• Direct filtering using df[...] - prefer using `&`/ `|`for AND & OR.  
• Inside query() strings - prefer using `and` /`or` for AND & OR

## Why Use query()?

- Cleaner syntax
- Easier for complex filtering
- Similar to SQL WHERE clause
- Better readability

`df.query()` **Method**\
Query method provides us with SQL-like filtering. We can pass our query in a string.

In [53]:
# Example 1
df.query("aqi > 30 and temperature < 40")
# Example 2
my_country = "IN"
df.query("country == @my_country")

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6480,2025-11-04 18:25:17.554219,IN,Mumbai,19.076,72.878,45.820,86.378,19.605,7.877,42.399,0.432,91,10.045,89.524,9.220
6481,2025-11-04 19:25:17.554219,IN,Mumbai,19.076,72.878,30.901,37.578,24.789,6.175,27.457,0.696,61,20.684,45.327,5.640
6482,2025-11-04 20:25:17.554219,IN,Mumbai,19.076,72.878,43.462,53.136,20.056,8.264,60.784,0.893,86,26.774,72.434,0.766
6483,2025-11-04 21:25:17.554219,IN,Mumbai,19.076,72.878,27.480,58.907,41.722,8.539,59.209,0.361,104,6.142,39.544,9.526
6484,2025-11-04 22:25:17.554219,IN,Mumbai,19.076,72.878,25.216,53.843,29.847,6.027,25.765,0.980,74,20.644,57.349,2.674
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8275,2025-11-19 13:25:17.554219,IN,Chennai,13.083,80.271,49.155,55.463,39.243,5.377,63.833,1.104,98,35.132,41.035,8.725
8276,2025-11-19 14:25:17.554219,IN,Chennai,13.083,80.271,68.446,93.351,47.252,4.812,64.233,1.044,136,17.835,27.979,1.200
8277,2025-11-19 15:25:17.554219,IN,Chennai,13.083,80.271,45.443,92.973,37.465,7.832,55.838,0.681,93,15.386,32.531,9.636
8278,2025-11-19 16:25:17.554219,IN,Chennai,13.083,80.271,41.327,104.353,39.472,5.130,40.228,0.811,104,37.014,66.142,5.292
8279,2025-11-19 17:25:17.554219,IN,Chennai,13.083,80.271,53.623,48.233,58.153,6.043,52.684,0.722,145,25.023,81.638,7.494

---
## Important DataFrame Methods

| Method | Purpose |
|----------|----------|
| head() | First rows |
| tail() | Last rows |
| shape | Dataset dimensions |
| columns | Column names |
| info() | Dataset information |
| describe() | Statistics |